package com.lifelineai.backend.entity;

public enum ToxicityPattern {
    GASLIGHTING,
    EMOTIONAL_MANIPULATION,
    THREATS_VIOLENCE,
    PHYSICAL_VIOLENCE,
    ISOLATION_TACTICS,
    FINANCIAL_CONTROL,
    STALKING_BEHAVIOR,
    JEALOUSY_POSSESSIVENESS,
    VERBAL_ABUSE,
    INTIMIDATION,
    LOVE_BOMBING,
    SEXUAL_COERCION,
    DIGITAL_ABUSE,
    PROPERTY_DESTRUCTION
}
